baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[permalinks]
  blog = "/blog/:year/:month/:title/"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

[author]
  name = "Dennis Juanito"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Dennis Juanito"
  keywords = "homepage, blog, software engineer, dennis juanito, blockchain, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # Default theme "light" or "dark"
  defaultTheme = "light"

  homeSubtitle = "Half Software Engineer ½  Blockchain Engineer"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/djuani0x"

  [[params.social]]
    name = "email"
    url  = "djuanito@ucsd.edu"

  [[params.social]]
    name = "github"
    url  = "https://github.com/djuanit0x"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/dennis-j/"

[languages]
  [languages.en]
    title = "Dennis Juanito"
    keywords = "homepage, blog, software engineer, dennis juanito, blockchain, development, programming"
    readOtherPosts = "Read other posts"
  [languages.en.params.logo]
    logoText = "djuanit0x"
    logoHomeLink = "/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
